# Site settings
title: Sugar Dreams
email: 3256453609@qq.com
description: > # this means to ignore newlines until "baseurl:"
 You got a dream,you gotta protect it.People can’t do something themselves,
 they wanna tell you you can’t do it.If you want something,go get it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wanwan745.github.io" # the base hostname & protocol for your site
twitter_username: Sugar Dreams
github_username:  wanwan745

# Build settings
markdown: kramdown
